from utilities import regedit

class Priority():
    def __init__(self) -> None:
        pass

    def _advancedPriorityTweaks(self):
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\HardCap0","CapPercentage",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\HardCap0","SchedulingType",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\Paused","CapPercentage",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\Paused","SchedulingType",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\SoftCapFull","CapPercentage",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\SoftCapFull","SchedulingType",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\SoftCapLow","CapPercentage",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\SoftCapLow","SchedulingType",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\BackgroundDefault","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Frozen","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenDNCS","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenDNK","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenPPLE","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Paused","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\PausedDNK","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Pausing","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\PrelaunchForeground","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\ThrottleGPUInterference","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\BackgroundDefault","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Frozen","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenDNCS","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenDNK","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenPPLE","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Paused","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\PausedDNK","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Pausing","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\PrelaunchForeground","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\ThrottleGPUInterference","IsLowPriority",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Critical","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Critical","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\CriticalNoUi","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\CriticalNoUi","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\EmptyHostPPLE","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\EmptyHostPPLE","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\High","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\High","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Low","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Low","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Lowest","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Lowest","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Medium","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Medium","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\MediumHigh","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\MediumHigh","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\StartHost","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\StartHost","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryHigh","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryHigh","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryLow","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryLow","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\IO\NoCap","IOBandwidth",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Memory\NoCap","CommitLimit",4294967295)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Memory\NoCap","CommitTarget",4294967295)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Critical","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Critical","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\CriticalNoUi","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\CriticalNoUi","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\EmptyHostPPLE","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\EmptyHostPPLE","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\High","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\High","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Low","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Low","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Lowest","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Lowest","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Medium","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Medium","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\MediumHigh","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\MediumHigh","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\StartHost","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\StartHost","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryHigh","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryHigh","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryLow","BasePriority",82)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryLow","OverTargetPriority",50)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\IO\NoCap","IOBandwidth",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Memory\NoCap","CommitLimit",4294967295)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Memory\NoCap","CommitTarget",4294967295)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\893dee8e-2bef-41e0-89c6-b55d0929964c","ValueMax",100)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\893dee8e-2bef-41e0-89c6-b55d0929964c\DefaultPowerSchemeValues\8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c","ValueMax",100)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583","ValueMin",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583","ValueMax",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ControlSet001\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583","ValueMax",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ControlSet001\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583","ValueMin",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ControlSet002\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583","ValueMax",0)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ControlSet002\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583","ValueMin",0)

    def _win32PrioritySeparation(self):
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\ControlSet001\Control\PriorityControl","Win32PrioritySeparation",38)
        regedit._setHKLMdwordREG('PRIORITY',r"SYSTEM\CurrentControlSet\Control\PriorityControl","Win32PrioritySeparation",38)

    def _doAll(self):
        self._advancedPriorityTweaks()
        self._win32PrioritySeparation()